MyAnimeList/Controllers/AnimesController.cs
using Microsoft.AspNetCore.Mvc;
using Service.Interface;
using Service.Implementation;
using Models.DomainModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.IdentityModel.Tokens;
using Models.DTO;
using Models.Enums;
using System.Security.Claims;

namespace MyAnimeList.Web.Controllers
{
    public class AnimesController : Controller
    {
        private readonly DataFetchService _dataFetchService;
        private readonly IAnimeService _animeService;
        private readonly IUnwatchedAnimeService _unwatchedAnimeService;
        private readonly UserManager<User> _userManager;

        public AnimesController(DataFetchService dataFetchService, IAnimeService animeService, IUnwatchedAnimeService unwatchedAnimeService, UserManager<User> userManager)
        {
            _dataFetchService = dataFetchService;
            _animeService = animeService;
            _unwatchedAnimeService = unwatchedAnimeService;
            _userManager = userManager;
        }

        [Route("/")]
        [Route("/Animes")]
        public async Task<IActionResult> Index(string? keyword, int page=1)
        {
            PaginatedResponse response = await _animeService.GetAll(keyword, page);
            if (!keyword.IsNullOrEmpty())
                ViewBag.Keyword = keyword;
            List<Anime> allAnimes = response.Animes;
            if (User.Identity.IsAuthenticated)
            {
                List<AnimeStatus> statuses = _unwatchedAnimeService.AlreadyInWatchList(allAnimes, _userManager.GetUserId(User));
                ViewBag.Statuses = statuses;
                ViewBag.IsAuth = true;
            }
            else
                ViewBag.IsAuth = false;
            ViewBag.Page = response.Page;
            return View(allAnimes);
        }

        public IActionResult GetAnimeById(Guid id, AnimeStatus status)
        {
            Anime? anime = _animeService.GetById(id);
            if(anime == null)
            {
                return RedirectToAction(nameof(Index));
            }
            ViewBag.Status = status;
            return View("AnimeDetails", anime);
        }

        [Authorize]
        public IActionResult AddToList(Guid id)
        {
            Anime? anime = _animeService.GetById(id);
            string? userIdStr = _userManager.GetUserId(User);
            if(anime == null)
            {
                TempData["Error"] = "Anime not found.";
                return RedirectToAction(nameof(Index));
            }
            var unwatched = _unwatchedAnimeService.GetByUserAndAnimeId(userIdStr, id);
            if(unwatched != null)
            {
                TempData["MessageType"] = MessageType.Info;
                TempData["Message"] = "This anime is already added to your watch list";
                return RedirectToAction(nameof(Index));
            }
                _unwatchedAnimeService.AddToList(userIdStr, anime);
                TempData["MessageType"] = MessageType.Success;
                TempData["Message"] = $"Added {anime.Name} to watch list";
                return RedirectToAction(nameof(Index));
        }
    }
}

MyAnimeList/Controllers/ReviewsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Models.Enums;
using Models.DomainModels;
using Service.Interface;
using Newtonsoft.Json;

namespace MyAnimeList.Web.Controllers
{
    public class ReviewsController : Controller
    {
        private readonly IReviewService _reviewService;
        private readonly IAnimeService _animeService;
        private readonly IUnwatchedAnimeService _unwatchedAnimeService;
        private readonly UserManager<User> _userManager;


        public ReviewsController(IReviewService reviewService, IAnimeService animeService, UserManager<User> userManager, IUnwatchedAnimeService unwatchedAnimeService)
        {
            _reviewService = reviewService;
            _animeService = animeService;
            _userManager = userManager;
            _unwatchedAnimeService = unwatchedAnimeService;
        }

        public IActionResult Index(Guid animeId)
        {
            var anime = _animeService.GetById(animeId); 
            return View(anime);  
        }
        public IActionResult GetAllReviewsForAnime(Guid animeId)
        {
            var anime = _animeService.GetById(animeId);
            var allReviews = _reviewService.GetAllReviewsByAnimeId(animeId);
            ViewBag.Anime = anime;
            
            return View(allReviews);
        }
        [HttpPost]
        [Authorize]
        public IActionResult AddReview(Guid animeId, string comment, int rating)
        {
            var userId = _userManager.GetUserId(User);
            var review = _reviewService.AddReview(animeId, userId, rating, comment);
            TempData["MessageType"] = MessageType.Success;
            TempData["Message"] = "Successfully added review!";
            return RedirectToAction("Index", new { animeId });
        }
        public IActionResult UpdateReview(Guid animeId)
        {
            var userId = _userManager.GetUserId(User);
            var review = _reviewService.GetReview(animeId, userId);
            TempData["Content"] = review.Content;
            TempData["Rating"] = review.Rating;
            return RedirectToAction("Index", new { review.AnimeId });
        }
        [HttpPost]
        [Authorize]
        public IActionResult UpdateReviewPost(Guid animeId, string comment, int rating)
        {
            var userId = _userManager.GetUserId(User);
            var review = _reviewService.UpdateReview(animeId, userId, rating, comment);
            TempData["MessageType"] = MessageType.Success;
            TempData["Message"] = "Successfully updated review!";
            TempData["Content"] = review.Content;
            TempData["Rating"] = review.Rating;
            return RedirectToAction("Index", new { animeId });
        }
        [HttpPost]
        [Authorize]
        public IActionResult AddReplyToReview(Review review, string reply)
        {
            _reviewService.AddCommentToReview(review.Id, reply);
            TempData["MessageType"] = MessageType.Success;
            TempData["Message"] = "Successfully posted a comment to this review";
            return RedirectToAction(nameof(GetAllReviewsForAnime), review.AnimeId);
        }

        public IActionResult RemoveReview(Guid animeId)
        {
            var userId = _userManager.GetUserId(User);
            var review = _reviewService.GetReview(animeId, userId);
            _unwatchedAnimeService.UpdateStatus(animeId, userId, AnimeStatus.Completed);
            _reviewService.RemoveReview(review);
            TempData["MessageType"] = MessageType.Success;
            TempData["Message"] = "Successfully deleted review";
            return RedirectToAction("Index", "WatchList");
        }
    }
}

MyAnimeList/Views/Animes/AnimeDetails.cshtml
@using Models.DomainModels
@using Models.Enums

@model Anime
@{
	ViewData["Title"] = "Model Details";
	ViewData["Layout"] = "~/Pages/Shared/_Layout.cshtml";
}

<div class="container row">
	<h2 class="mb-lg-4 mb-2">@Model.Name</h2>
	<div class="col-3">
		<img src="@Model.ImageUrl" alt="@Model.Name" class="w-100" style="max-height: 460px" />
	</div>
	<div class="col-8 d-flex flex-column justify-content-center">
		<p><strong>Title Japanese: </strong> @Model.NameJapanese</p>
		<p><strong>Year aired: </strong> @(Model.YearAired==null ? "N/A" : Model.YearAired) </p>
		<p>
			<strong>Genre: </strong>
				@foreach (var genre in Model.Genres) { <span> @genre </span> }
		</p>
		<p><strong>Number of episodes: </strong>@(Model.NumberOfEpisodes==null ? "N/A" : Model.NumberOfEpisodes)</p>
		<p><strong>Rating: </strong>@(Model.Rating==null ? "N/A" : Model.Rating)</p>
		<p>
			<strong>Synopsis: </strong>
			<p>@Model.Description</p>
		</p>
		<div>
			@if(ViewBag.Status==AnimeStatus.NotInList){
				<a asp-controller="Animes" asp-route-id="@Model.Id" class="btn btn-primary">Add To List</a>
			}
			else if(ViewBag.Status==AnimeStatus.Completed){
				<a asp-controller="Rating" asp-action="AddRating" asp-route-id="@Model.Id" class="btn btn-primary">Add To List</a>
			}
			else{
				<a asp-controller="WatchList" asp-action="Index" class="btn info-box">To Watch List</a>
			}
		</div>
	</div>
</div>

MyAnimeList/Views/Animes/Index.cshtml
@using Models.DomainModels
@using Models.Enums


@model List<Anime>
@{
	ViewData["Title"] = "All";
	Layout = "~/Pages/Shared/_Layout.cshtml";
	bool isAuthenticated = User.Identity.IsAuthenticated;
}

@if (TempData["Error"] != null)
{
	ViewData["MessageType"] = "error";
	ViewData["Message"] = TempData["Error"];
	@await Html.PartialAsync("InfoBox", ViewData)
}
@if (TempData["Message"] != null)
{
	ViewData["MessageType"] = TempData["MessageType"];
	ViewData["Message"] = TempData["Message"];
	@await Html.PartialAsync("InfoBox", ViewData)
}

<h1>All Animes</h1>
<div class="main">
	<form asp-action="Index" method="get" class="keyword-search-form">
		<input type="text" name="keyword" value="@(ViewBag.Keyword ?? "")" placeholder="Search anime" />
		<button type="submit" class="btn bg-lilac-1">Search</button>
	</form>
	<div class="row">
		@for(int i=0; i<Model.Count; i++)
		{
			var anime = Model[i];
			<div class="col-4 p-3">
				<div class="card border-lilac-1">
					<img src="@anime.ImageUrl" alt="@anime.Name" class="card-img-top border-lilac-1" style="max-height: 300px;"/>
					<div class="card-body">
						<a asp-action="GetAnimeById" asp-route-id="@anime.Id" asp-route-status="@(isAuthenticated? ViewBag.Statuses[i] : AnimeStatus.NotInList)" class="card-title text-lilac-1">@anime.Name</a>
						<p><strong>Year aired: </strong> @(anime.YearAired==null? "N/A":anime.YearAired)</p>
						<p><strong>Genre: </strong>
							@foreach (var genre in anime.Genres)
							{
								<span>
									@genre 
								</span>

							}
						</p>
						<p><strong>Number of episodes: </strong>@anime.NumberOfEpisodes</p>
						<p><strong>Rating: </strong>@anime.Rating</p>
						@if (isAuthenticated)
						{
							AnimeStatus status = ViewBag.Statuses[i];
							<p><strong>Status: </strong>
								<div> @await Html.PartialAsync("StatusDot", status)</div>
							</p>
						}
						<p><strong>Synopsis: </strong>
							@if (!string.IsNullOrEmpty(anime.Description) && anime.Description.Length > 100)
							{
								@anime.Description.Substring(0, 100)
								<a asp-controller="Animes" asp-action="GetAnimeById" asp-route-id="@anime.Id" asp-route-status="@(isAuthenticated? ViewBag.Statuses[i] : AnimeStatus.NotInList)">
									See more </a>
							}
							else
							{
								@anime.Description
							}
						</p>
					</div>
					<div class="w-100 d-flex justify-content-between" style="padding: 16px">
						<a asp-controller="Reviews" asp-action="GetAllReviewsForAnime" asp-route-animeId="@anime.Id" class="btn btn-yellow-1 bottom-left-corner">
							See reviews
						</a>
						@if (ViewBag.Statuses == null || ViewBag.Statuses[i]==AnimeStatus.NotInList)
						{
							<a asp-controller="Animes" asp-action="AddToList" asp-route-id="@anime.Id" class="btn bottom-right-corner btn-lilac-1" style="padding: 10px;">
								Add To List
							</a>
						}
						else
						{
							<span class="success-box bottom-right-corner">Added to Watch List</span>
						}
					</div>
				</div>
			</div>
		}
	</div>
	<form asp-action="Index" method="get" class="pages-bar">
		@{
			int prev = ViewBag.Page.current_page  - 1;
			int next = ViewBag.Page.current_page  + 1;
		}
		<button type="submit" disabled="@(prev<1)" name="page" value="@prev">Previous page</button>
		<span>Page @ViewBag.Page.current_page out of @ViewBag.Page.last_visible_page</span>
		<button type="submit" disabled="@(!ViewBag.Page.has_next_page)" name="page" value="@next">Next page</button>
	</form>
</div>

<style>
	.main{
		display: flex;
		justify-content: center;
		padding: 1rem 10%;
		flex-wrap: wrap;
	}
	.card {
		height: 100%;
	}
	.card-title{
		height: 60px;
		text-decoration: none;
		font-size: 22px;
		font-weight: bold;
		display: inline-block;
		line-height: 2rem;
	}
	.pages-bar{
		width: 70%;
		text-align: center;
		margin: 1rem 0;
	}
	.keyword-search-form{
		font-size: 1.2rem;
		margin-bottom: 3rem;
		width: 70%;
		display: flex;
		align-items: center;
	}
	.keyword-search-form input {
		width: 80%;
		height: 2rem;
		box-sizing: border-box;
		padding: 20px 10px;
		border-radius: 10px;
		margin-right: 10px;
		border-color: #832be3;
	}
    .keyword-search-form button{
		width: 15%;
		font-size: 1.2rem;
		height: 40px;
		box-sizing: border-box;
		color: white;
	}
	/* .bottom-right-corner { */
	/* 	position: absolute; */
	/* 	right: 10px; */
	/* 	bottom: 10px; */
	/* } */
	/* .bottom-right-corner { */
	/* 	position: absolute; */
	/* 	left: 10px; */
	/* 	bottom: 10px; */
	/* } */
</style>