MyAnimeList/Controllers/AnimesController.cs
using Microsoft.AspNetCore.Mvc;
using Service.Interface;
using Service.Implementation;
using Models.DomainModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.IdentityModel.Tokens;
using Models.DTO;
using Models.Enums;
using System.Security.Claims;

namespace MyAnimeList.Web.Controllers
{
    public class AnimesController : Controller
    {
        private readonly DataFetchService _dataFetchService;
        private readonly IAnimeService _animeService;
        private readonly IUnwatchedAnimeService _unwatchedAnimeService;
        private readonly UserManager<User> _userManager;

        public AnimesController(DataFetchService dataFetchService, IAnimeService animeService, IUnwatchedAnimeService unwatchedAnimeService, UserManager<User> userManager)
        {
            _dataFetchService = dataFetchService;
            _animeService = animeService;
            _unwatchedAnimeService = unwatchedAnimeService;
            _userManager = userManager;
        }

        [Route("/")]
        [Route("/Animes")]
        public async Task<IActionResult> Index(string? keyword, int page=1)
        {
            PaginatedResponse response = await _animeService.GetAll(keyword, page);
            if (!keyword.IsNullOrEmpty())
                ViewBag.Keyword = keyword;
            List<Anime> allAnimes = response.Animes;
            if (User.Identity.IsAuthenticated)
            {
                List<AnimeStatus> statuses = _unwatchedAnimeService.AlreadyInWatchList(allAnimes, _userManager.GetUserId(User));
                ViewBag.Statuses = statuses;
                ViewBag.IsAuth = true;
            }
            else
                ViewBag.IsAuth = false;
            ViewBag.Page = response.Page;
            return View(allAnimes);
        }

        public IActionResult GetAnimeById(Guid id, AnimeStatus status)
        {
            Anime? anime = _animeService.GetById(id);
            if(anime == null)
            {
                return RedirectToAction(nameof(Index));
            }
            ViewBag.Status = status;
            return View("AnimeDetails", anime);
        }

        [Authorize]
        public IActionResult AddToList(Guid id)
        {
            Anime? anime = _animeService.GetById(id);
            string? userIdStr = _userManager.GetUserId(User);
            if(anime == null)
            {
                TempData["Error"] = "Anime not found.";
                return RedirectToAction(nameof(Index));
            }
            var unwatched = _unwatchedAnimeService.GetByUserAndAnimeId(userIdStr, id);
            if(unwatched != null)
            {
                TempData["MessageType"] = MessageType.Info;
                TempData["Message"] = "This anime is already added to your watch list";
                return RedirectToAction(nameof(Index));
            }
                _unwatchedAnimeService.AddToList(userIdStr, anime);
                TempData["MessageType"] = MessageType.Success;
                TempData["Message"] = $"Added {anime.Name} to watch list";
                return RedirectToAction(nameof(Index));
        }
    }
}

MyAnimeList/Controllers/WatchListController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Models.DomainModels;
using Models.Enums;
using Service.Interface;

namespace MyAnimeList.Web.Controllers
{
    public class WatchListController : Controller
    {
        private readonly IUnwatchedAnimeService _unwatchedAnimeService;
        private readonly UserManager<User> _userManager;
        private List<UnwatchedAnime> myList;

        public WatchListController(IUnwatchedAnimeService unwatchedAnimeService, UserManager<User> userManager)
        {
            _unwatchedAnimeService = unwatchedAnimeService;
            _userManager = userManager;
            myList = new List<UnwatchedAnime>();
        }

        [Authorize]
        public IActionResult Index(AnimeStatus? status)
        {
            string? id = _userManager.GetUserId(User);
            myList = status == null ?
                _unwatchedAnimeService.GetAllByUser(id) :
                _unwatchedAnimeService.GetByStatus(id, status.Value);
            var statusCountDictionary = _unwatchedAnimeService.GetCountByStatus(id);
            ViewBag.StatusCount = new Dictionary<AnimeStatus, int>();
            ViewBag.Status = status ?? AnimeStatus.All;
            foreach (AnimeStatus s in Enum.GetValues(typeof(AnimeStatus))) {
                if (statusCountDictionary.ContainsKey(s))
                    ViewBag.StatusCount[s] = statusCountDictionary[s];
                else
                    ViewBag.StatusCount[s] = 0;
            }
            return View(myList);
        }
        public IActionResult RemoveFromList(Guid id)
        {
            var removed = _unwatchedAnimeService.RemoveFromList(id);
            TempData["Message"] = $"Successfully removed {removed?.Anime?.Name ?? "anime"} from Watch List!";
            TempData["MessageType"] = MessageType.Success;
            return RedirectToAction(nameof(Index));
        }
        public IActionResult UpdateStatus(Guid id, AnimeStatus status)
        {
            var unWatched = _unwatchedAnimeService.GetById(id);
            unWatched.Status = status;
            _unwatchedAnimeService.Update(unWatched);
            TempData["Message"] = $"Changed status of {unWatched?.Anime?.Name ?? "anime"} to {StatusReader.StatusToString(status)}!";
            TempData["MessageType"] = MessageType.Info;
            return RedirectToAction(nameof(Index));
        }
    }
}

MyAnimeList/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MyAnimeList</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MyAnimeList.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/scss/site.scss" asp-append-version="true"/>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand text-lilac-3" asp-area="" asp-controller="Animes">MyAnimeList</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="WatchList">My Watch List</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - MyAnimeList - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>